---
# title: "About"


tbl-cap-location: top
fig-cap-location: top

css: "../../additional_styles/styles_chapter5_1_EmpricialStrategy.css"

sidebar:
    logo: "../../assets/cover.jpg"
    
format:
  html:
    include-in-header:
      - text: |
         <link rel="icon" type="image/png" href="../../assets/cover.jpg">
---

# 5.1 Hedonic model

::: paratext
The primary methods utilised to quantify the premium or capitalisation of energy efficient amenities are either through the discrete choice framework or a hedonic approach following @rosen_hedonic_1974, @lancaster_new_1966 and @brown_estimation_1982. In both these methodologies, it is assumed that the market is competitive with a short-term fixed supply. Moreover, consumers maximise their utility function by weighing a home's attributes, price and individual trades while staying within budget constraints. Most literature estimating price premiums on energy efficiency labels or energy performance utilises a hedonic model, and this thesis will do the same.

The hedonic model essentially consists of regressions of house value against the characteristics of the unit that determine the value. As a simple example, the dwelling price function can be computed as follows:

$$
V = f(X,G,Q,E)
$$ {#eq-utility}

Where V represents the market value of the property (here transaction price); X is a vector of variables describing property characteristics; G is a vector of geographical factors which describes the surroundings of the property and any location attributes (e.g., distance to the central business district, etc.). Q is a vector of variables quantifying the quality/condition of the property, and E represents a vector of energy-efficient variables. To quantify the attribute's effect on price in an econometrics setting, the majority of studies employ a hedonic regression, as will we. As Figure @fig-literature_variables shows, most studies use a logarithmic transformation for their dependent variable, as demonstrated below:

$$
\ln(V) = \beta_{0} + \beta_{1} \mathbf{X} + \beta_{2} \mathbf{G} + \beta_{3} \mathbf{Q} + \beta_{4} \mathbf{E} + e
$$ {#eq-logarithm}

Where e is the error term capturing unobserved factors affecting property prices. @malpezzi_hedonic_2002 points out that the log-linear form has a couple of advantages. Among the benefits he points out is that taking the logarithm of the dependent variable offers a more straightforward and more appealing interpretation. As an example, if the coefficient of a variable representing energy efficiency, such as the label B, is 0,065, then the approximation of the percentage change can be derived using the method constructed by @halvorsen_interpretation_1980,

which is $e^{coefficient}-1$. This means that energy label B will add 6.72% more value to the property. Furthermore, by transforming the dependent variable using natural logarithms, we can reduce the issue of heteroskedasticity. In statistics, heteroskedasticity arises when the error term has varying variance across different levels of the independent variables—for example, considering a regression model where we want to predict housing prices based on dwelling size. Let's assume that our data shows that the price varies a lot more for smaller properties than for more extensive properties. If we fail to account for this heteroskedasticity, then it will lead to inefficient estimates of our standard errors.

In an ideal setting, we would like to observe house prices of identical properties over time and rewind to manipulate their energy performance to different levels, observing the resulting price changes. However, in our case, such experiments are not feasible in reality. Instead, we rely on statistical methods and data on various factors that constitute the properties attributes, including energy performance, to estimate how changes in these factors affect house prices. We will turn to the Ordinary Least Square (OLS) regression for statistical methods. A standard tool to quantify how changes, such as improving energy efficiency, affect property prices. However, as with any statistical analysis, specific problems may arise and must be addressed before conclusions can be reached without the risk of biased estimations. One problem is that this study relies on a sample that is not randomised. When a sample lacks randomisation, there is a risk of biased estimated effects, which can significantly affect the conclusion drawn from the study. The degree of bias hinges on the correlation between the error term and the independent variable, e.g., the energy performance of the property. If the error term correlates with the variable, it introduces endogeneity, which can skew the results. This correlation can lead to either overestimating or underestimating the variable coefficient.

Moreover, to quantify the causal effect of a variable, for example, energy performance, one must consider other valued attributes of the property. However, given @eq-logarithm, energy performance (E) might be linked to the presence or absence of various energy-efficient attributes within the property. These features typically encompass lighting and heating systems, insulation quality, water heating, window glazing and construction years. This suggests that there is a correlation between Q and E. Consequently, even if we were to add a variety of variables into our estimation, we run the risk of introducing potential multicollinearity to our estimates.

Furthermore, another significant challenge in estimating the causal effect is omitted variable bias. Omitted variable bias occurs when important variables are not accounted for in the model. In other words, if we do not account for a variable that influences both the sales price and the property's energy performance, then we will incorporate that effect into the variable of interest and thereby either overestimate or underestimate the true effect. Take, for instance, energy performance and construction year. These two variables often correlate, in particular since that building standards have changed such that new buildings must be within a specific energy performance range. Construction years can positively affect the sales price of the property and its energy performance. However, when a variable, such as construction year, is omitted from the regression model, then we introduce the risk of overestimating or underestimating the impact of energy performance.

A number of scholars have pointed out that the traditional hedonic model suffers from sample selection bias (see e.g. @stenvall_does_2022, @wilhelmsson_energy_2019, @naess-schmidt_homes_2015). This is a bias that occurs when using non-random data for statistical analysis. As @stenvall_does_2022 point out in their study, energy-efficient and non-energy-efficient properties might differ in terms of characteristics, i.e. energy-efficient properties might have unique attributes that distinguish them from properties that do not prioritise energy efficiency. Therefore, the causal effect might be distributed non-randomly. In general, one can expect that older buildings tend to have lower energy efficiency than newer buildings. Consequently, as stated by @stenvall_does_2022, when performing analyses, there arises a potential discrepancy between the two groups, i.e. energy, efficient and non-energy efficient properties, in relation to the age of the property. Even though one does control for age, there remains uncertainty regarding the accuracy of the model's representation of this relationship. This uncertainty extends to the structure of the relationship, whether it's linear or non-linear.

It is crucial to acknowledge the challenges faced with when conducting a statistical analysis, as they can pose significant challenges to the interpretation of results. Throughout this thesis, it is imperative to remain mindful of these biases. Next, we shift our focus on to the empirical strategy best suited for addressing various challenges outlined above.
:::