project:
  type: book
  output-dir: docs



book:
  title: Are home buyers inattentive towards energy efficiency?
  subtitle: An econometric analysis based on a new data set created with NLP and OCR techniques
  author: "Valdimar Einarsson"
  date: "2024-7-22"
  chapters:
    - index.qmd
    - quarto_files/introduction.qmd
    - quarto_files/epbd_and_danish_EPC_scheme.qmd
    - quarto_files/literature_review.qmd
    - part: "4. Data"
      chapters: 
        - quarto_files/data/data_housing.qmd
        - quarto_files/data/data_EPC.qmd
        - quarto_files/data/data_geo.qmd
    - part: "5. Empirical Strategy"
      chapters: 
        - quarto_files/empirical_strategy/empirical_strategy_HedonicModel.qmd
        - quarto_files/empirical_strategy/empirical_strategy_EstimationStrategy.qmd
    - part: "6. Results"
      chapters: 
        - quarto_files/results/main_result.qmd
        - quarto_files/results/market_segment_property_type.qmd
        - quarto_files/results/policy_effect.qmd
        - quarto_files/results/robustness_tests.qmd
    # - quarto_files/results.qmd
    - quarto_files/discussion.qmd
    - quarto_files/references.qmd
    - quarto_files/appendix.qmd

  
  # ---> The horizontal Navigation bar
  navbar:
    title: false #Remove the website title
    left:
      - href: index.qmd  #change to portfolio website
        icon: arrow-left-circle
        text: Home


  # ---> Sidebar setup : the paper
  sidebar:
    logo: "assets/cover.jpg"
    pinned: true # Have it fixed (pinned) on page
    style: docked
    alignment: center
    tools:
      - icon: house-fill
        href: index.html
        text: "Home"
      - icon: github
        href: https://github.com/valdikaldi/Empirical_Project-are_home_buyers_inattentive_towards_energy_efficiency
        text: "My github"
        
  # ---> The Search bar
  search:
    location: sidebar
    type: textbox

  # ---> set page footer
  page-footer:
    right: "Built using [Quarto](https://quarto.org/)."
    left: "&copy; CC-Valdimar, 2024"


bibliography: references.bib

format:
  html:
    toc-title: On this page
    toc-expand: 3
    code-fold: true
    number-sections: false

    theme:
      light: cosmo
      dark: darkly
    
    css: 
      - main_styles.css
    
    grid:
      body-width: 1100px
      sidebar-width: 250px
      margin-width: 180px
      gutter-width: 1.5rem
    # add icon to the browser tab
    include-in-header:
      - text: |
         <link rel="icon" type="image/png" href="assets/cover.jpg">

editor: visual

