---
tbl-cap-location: top
fig-cap-location: top

css: "../additional_styles/styles_chapter2_EPC.css"

sidebar:
    logo: "../assets/cover.jpg"
    
format:
  html:
    include-in-header:
      - text: |
         <link rel="icon" type="image/png" href="../assets/cover.jpg">
---

# 2. EPBD and the Danish EPC scheme

:::: paratext
With the establishment of the Energy Performance of Buildings Directive (EPBD) in 2001, the EU constructed its main legislative tool to improve the energy performance of buildings. With this Directive, EU members were given a framework to develop regulations for the energy efficiency of buildings. The framework provided a rounded structure on matters such as defining energy performance and methodology to quantify and measure the energy efficiency of buildings [@ec_eu_2002]. Thus, the EU Commission highlighted the importance of energy conservation in buildings and formulated the EPC system. From 2006 onwards, the EPC system was gradually implemented across member states, with all states mandated to have an operational system in place by the final deadline of 4 January 2009 [@arcipowska_energy_2014]. Since 2002, the EU Commission has updated the Directive through the years. In 2010, the EU recast the EPBD (European Directive 2010/31/EU) by updating the previous Directive as well as improving the quality of the Energy Performance Certification scheme by implementing additional requirements regarding independent qualified and/or accredited experts authorised to perform assessments of a building's energy performance [@eu_eu_2010]. Moreover, The EU Commission later expanded the scope of the recast in January 2012 by introducing a comparative methodology framework to determine the most cost-effective levels of minimum energy performance standards for both buildings and building elements. The recast of the EPBD played a vital role in enhancing transparency in the methodology of the energy performance of buildings and minimising potential information asymmetries between the property buyer and seller. Before the recast, sellers were not obligated to publicly display the energy performance of the property. Sellers could simply showcase the certificate at the time of signing the purchase agreement or rental contract. However, this changed with the recast, which required that when buildings

::: paratext_quote
“are offered for sale or for rent, the energy performance indicator of the energy performance certificate of the building or the building unit, as applicable, is stated in the advertisements in commercial media” [@eu_eu_2010, page 24]
:::

The fundamental motivations of the recast was to push for more sustainable development and make critical information more accessible to potential buyers and renters such that it fosters greater demand for energy-efficient buildings. By doing so, the goal is to reduce energy consumption and greenhouse gas emissions in the housing sector. As a result, EPCs simplify the procedure of comparing similar buildings and can help boost awareness in the market towards energy efficiency, which intends to assist the EU in achieving its sustainability goals. [@arcipowska_energy_2014]

Members of the European Union have a degree of freedom to develop their measurement systems, accreditation requirements, and EPC layouts under the subsidiarity principle. Nevertheless, they are required to be in line with the EU framework policy given in the EPBD and meet the minimum methodology requirement specified in Annex 1 in the Directive. Certain key information must be displayed in the EPCs to fulfil EPBD requirements. This includes the energy performance index, which reflects the energy efficiency rating of the building, as well as reference values, such as minimum energy performance requirements, enabling comparison between different buildings. Expert recommendations are also required, where possible, and feasible home renovations that can improve the energy performance of the building are listed. Finally, the methodology estimate needs to be standardised at the national level. [@eu_eu_2010]

A report made by @arcipowska_energy_2014 gives a clear overview of the implementation of EPC across the EU and the different countries that implement an EPC scheme. From the report, it can be seen that over the course of the implementation, the majority of countries have developed a letter-based rating scheme, for instance, on a scale from A to G, where A is most efficient and G is least efficient. These ratings are determined either based on specific energy consumption values or by comparing the building's performance to reference buildings. Furthermore, the majority of countries have made it a requirement that qualified experts must make an on-site visit to the property to issue an energy performance certificate for existing buildings, that includes Denmark. The on-site requirement is one of the ways to ensure that the quality of the input data is upheld for the calculation process.

Since the year 1997, it has been mandatory in Denmark to have an energy certification. Denmark was the first EU member to construct a complete building certification scheme, which consisted of an energy performance label system ranging from labels A to G. The Danish Energy Agency projected a positive impact on market activity by promoting the sale of highly energy-efficient buildings from an early implementation. Additionally, Danish policymakers argued that the implementation of the energy performance rating for buildings would not only raise the energy efficiency standards of the building stock, but would also serve as an important motivator in driving the society's overall efforts towards reducing carbon emissions [@jensen_market_2016]. As a result, starting from 1 January 1997, every building that was listed for sale was required to have a valid energy performance rating [@jensen_market_2016]. Interestingly, @jensen_market_2016 point out in their paper that even though Denmark became one of the first EU members to implement a scheme, there was no observable effect for 15 years. The Danish authorities implemented the 2010 EBPD recast almost two weeks after it got passed, i.e. on 1 July 2010. One year later, an effect was observed on the market. Danish real estate agents claimed that the easiest properties to sell were properties with higher energy performance. [@jensen_market_2016]

The Danish EPC scheme is maintained by the Danish Energy Agency (DEA). They are responsible for monitoring, maintaining quality assurance, and conducting further developments on the program. In order to receive an EPC report for a given building, a property must be inspected by a licensed energy consultant, which then will determine the building's energy performance [@concerted_action_epbd_implementation_2020]. The licensed energy consultant calculates the building's energy consumption and signs a label on a scale from A to G, where A indicates the highest energy standard and G the lowest. He inspects the building's quality concerning insulation, windows and doors, heating installation system, heating sources, etc. On this basis, the building's energy consumption is calculated under certain assumptions such as weather, family size, operating hours, consumption habits, etc [@noauthor_energimaerkning_nodate]. In other words, the energy consumption is theoretical. However, it is set up to reflect normal household consumption, given the building's attributes. With that being said, it may not necessarily reflect the actual energy consumption, which is, of course, highly dependent on both the weather and the habits of the residence. Moreover, the EPC reports give an overview of the energy improvements that the energy consultants deem cost-effective to implement at the time of reporting.

Over the years, the energy labels in Denmark have changed multiple times. Table @tbl-EPC_table depicts the conversion from all the different energy labels that the Danish EPC scheme has had to the current labelling system, as well as the current official energy thresholds for each label. To this day, the A label in Denmark is split into three subcategories: A2020, A2015 and A2010. Where A2020 represents the most energy-efficient category, and G is labelled the least efficient. The 2013 scale is the official EPC labels in Denmark today. To this day, newly constructed buildings must have an energy label A2015 or A2020 [@noauthor_hvornar_2016]. As Table @tbl-EPC_table shows, a house of the size 100 square meters labelled D has an energy consumption between 167 (135+3200/100) and 217 (175+4200/100) kWh per square meter per year, i.e. between 16.700 to 21.700 kWh per year. On the other hand, a property of the same size with the label A2020 has an energy consumption equal to or less than 25 kWh per square meter per year i.e., 2,500 kWh per year or less.
::::

::: {#tbl-EPC_table}
+----------+----------+----------+----------+-----------------+-----------------------+
| 2006\    | 2008V1\  | 2008V2\  | 2011\    | 2013\           | Threshold limit\      |
| scale    | scale    | scale    | scale    | scale\          | 2013-\                |
|          |          |          |          | (Current scale) | $(kWh/m^2/year)$      |
+:========:+:========:+:========:+:========:+:===============:+:=====================:+
| \-       | \-       | \-       | \-       | A2020           | $$\le 25$$            |
+----------+----------+----------+----------+-----------------+-----------------------+
| A1       | \-       | \-       | A1       | A2015           | $$\le 41.0 + 1000/A$$ |
+----------+----------+----------+----------+-----------------+-----------------------+
| A2       | A        | A1,A2    | A2       | A2010           | $$\le 71.3 + 1650/A$$ |
+----------+----------+----------+----------+-----------------+-----------------------+
| B1       | B        | B        | B        | B               | $$\le 95.0 + 2200/A$$ |
+----------+----------+----------+----------+-----------------+-----------------------+
| B2,C1    | C        | C        | C        | C               | $$\le 135+ 3200/A$$   |
+----------+----------+----------+----------+-----------------+-----------------------+
| C2,D1    | D        | D        | D        | D               | $$\le 175 + 4200/A$$  |
+----------+----------+----------+----------+-----------------+-----------------------+
| D2,E1    | E        | E        | E        | E               | $$\le 215 + 5200/A$$  |
+----------+----------+----------+----------+-----------------+-----------------------+
| E2,F1    | F        | F        | F        | F               | $$\le 265 + 6500/A$$  |
+----------+----------+----------+----------+-----------------+-----------------------+
| F2,G1,G2 | G        | G        | G        | G               | $$> 265 + 6500/A$$    |
+----------+----------+----------+----------+-----------------+-----------------------+

: Conversion table - EPC classification for residential buildings
:::

::: text_footnote_fig_tables
Note: the letter A in column "Threshold limit 2013 $kWh/m^2/year$" represents that heated living area. Data taken from @klima-_energi-_og_forsyningsministeriet_bekendtgorelse_2015.
:::

::: paratext
As mentioned earlier, this thesis will analyse the period 1. July 2010 to 2023. To quantify the label effects across the whole sampling period, all labels from older labeling systems are converted into the newest system based on the conversion table. Furthermore, within the period of this study, the layout and design of the Danish EPC reports have had three major changes. This is important because not all designs convey the exact same information. For clarity, the designs of the certificates will be referred to as Design 1, Design 2, and Design 3, where Design 1 is the oldest and Design 3 is the newest. The biggest difference is between the first design and the other designs. Essentially the renovation recommendation includes the following information: the type of renovation, estimated investment cost, and energy cost saved. In all designs, the renovations are categorised into two groups: profitable renovations and other renovations. The first group represents so-called “profitable renovations,” i.e., renovations that the licensed energy expert deems profitable based on estimated costs and savings. A renovation is deemed profitable if the energy savings can pay back the investment before the proposed renovation needs to be replaced again. As an example, if the proposal is to replace a circulation pump for hot water, the pump is expected to last for 15 years, and the savings proposal is considered profitable if the estimated energy savings can pay back the investment over 15 years. The second group will be referred to as the “non-profitable renovations”, which represent renovation proposals that cannot repay the investment before the proposed renovation needs to be replaced again. However, these renovations are often beneficial to consider if the building is being renovated or if there are building components that need to be replaced anyway. The profitable renovations include both investment cost, energy savings in Danish krone (DKK), and energy consumption saved. For non-profitable renovations, only the energy savings in DKK and the energy consumption saved are included. In addition to this, both EPC designs 2 and 3 include the energy label that a building would get from implementing profitable renovations and the energy label it would get from implementing all renovations, i.e. both profitable and non-profitable renovations. However, design one only includes the potential energy label the property would get from all renovations. Overall, in [chapter 4: Data](data/data_housing.qmd) we will go in more detail how we harmonise our data over all the designs.
:::